//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub mod prelude;

pub mod event_address_authorized;
pub mod event_address_removed;
pub mod event_auction_finished;
pub mod event_land_bought;
pub mod event_new_auction;
pub mod event_nuked;
pub mod event_remaining_stake;
pub mod historical_land;
pub mod historical_land_stake;
