//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::event_address_authorized::Entity as EventAddressAuthorized;
pub use super::event_address_removed::Entity as EventAddressRemoved;
pub use super::event_auction_finished::Entity as EventAuctionFinished;
pub use super::event_land_bought::Entity as EventLandBought;
pub use super::event_new_auction::Entity as EventNewAuction;
pub use super::event_nuked::Entity as EventNuked;
pub use super::event_remaining_stake::Entity as EventRemainingStake;
pub use super::historical_land::Entity as HistoricalLand;
pub use super::historical_land_stake::Entity as HistoricalLandStake;
